spring:
  application:
    name: spring-service
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:smart_city}
    username: ${POSTGRES_USER:smart_city_user}
    password: ${POSTGRES_PASSWORD:smart_city_pass}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SPRING_SERVICE_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
